import type { State } from './types';

const gradients = [
  'from-purple-500 to-pink-500',
  'from-blue-500 to-cyan-500',
  'from-green-500 to-emerald-500',
  'from-orange-500 to-red-500',
  'from-indigo-500 to-purple-500',
  'from-violet-500 to-pink-500',
  'from-cyan-500 to-blue-500',
  'from-teal-500 to-green-500',
  'from-rose-500 to-pink-500',
  'from-amber-500 to-orange-500',
  'from-lime-500 to-green-500',
  'from-fuchsia-500 to-purple-500',
];

export const mexicanStates: State[] = [
  { id: '1', name: 'Aguascalientes', gradient: gradients[0] },
  { id: '2', name: 'Baja California', gradient: gradients[1] },
  { id: '3', name: 'Baja California Sur', gradient: gradients[2] },
  { id: '4', name: 'Campeche', gradient: gradients[3] },
  { id: '5', name: 'Chiapas', gradient: gradients[4] },
  { id: '6', name: 'Chihuahua', gradient: gradients[5] },
  { id: '7', name: 'Ciudad de México', gradient: gradients[6] },
  { id: '8', name: 'Coahuila', gradient: gradients[7] },
  { id: '9', name: 'Colima', gradient: gradients[8] },
  { id: '10', name: 'Durango', gradient: gradients[9] },
  { id: '11', name: 'Estado de México', gradient: gradients[10] },
  { id: '12', name: 'Guanajuato', gradient: gradients[11] },
  { id: '13', name: 'Guerrero', gradient: gradients[0] },
  { id: '14', name: 'Hidalgo', gradient: gradients[1] },
  { id: '15', name: 'Jalisco', gradient: gradients[2] },
  { id: '16', name: 'Michoacán', gradient: gradients[3] },
  { id: '17', name: 'Morelos', gradient: gradients[4] },
  { id: '18', name: 'Nayarit', gradient: gradients[5] },
  { id: '19', name: 'Nuevo León', gradient: gradients[6] },
  { id: '20', name: 'Oaxaca', gradient: gradients[7] },
  { id: '21', name: 'Puebla', gradient: gradients[8] },
  { id: '22', name: 'Querétaro', gradient: gradients[9] },
  { id: '23', name: 'Quintana Roo', gradient: gradients[10] },
  { id: '24', name: 'San Luis Potosí', gradient: gradients[11] },
  { id: '25', name: 'Sinaloa', gradient: gradients[0] },
  { id: '26', name: 'Sonora', gradient: gradients[1] },
  { id: '27', name: 'Tabasco', gradient: gradients[2] },
  { id: '28', name: 'Tamaulipas', gradient: gradients[3] },
  { id: '29', name: 'Tlaxcala', gradient: gradients[4] },
  { id: '30', name: 'Veracruz', gradient: gradients[5] },
  { id: '31', name: 'Yucatán', gradient: gradients[6] },
  { id: '32', name: 'Zacatecas', gradient: gradients[7] },
];

export const mexicanCities: { [key: string]: string[] } = {
  '1': ['Aguascalientes', 'Calvillo', 'Pabellón de Arteaga'],
  '2': ['Tijuana', 'Mexicali', 'Ensenada', 'Rosarito'],
  '3': ['La Paz', 'Los Cabos', 'Loreto'],
  '4': ['Campeche', 'Ciudad del Carmen'],
  '5': ['Tuxtla Gutiérrez', 'San Cristóbal de las Casas', 'Palenque'],
  '6': ['Chihuahua', 'Juárez', 'Delicias', 'Hidalgo del Parral'],
  '7': ['México', 'Benito Juárez', 'Miguel Hidalgo', 'Cuauhtémoc', 'Iztapalapa'],
  '8': ['Saltillo', 'Torreón', 'Monclova', 'Piedras Negras'],
  '9': ['Colima', 'Manzanillo', 'Tecomán'],
  '10': ['Durango', 'Gómez Palacio', 'Lerdo'],
  '11': ['Toluca', 'Ecatepec', 'Naucalpán', 'Nezahualcóyotl'],
  '12': ['Guanajuato', 'León', 'Irapuato', 'Salamanca'],
  '13': ['Acapulco', 'Chilpancingo', 'Iguala'],
  '14': ['Pachuca', 'Tulancingo', 'Tula'],
  '15': ['Guadalajara', 'Zapopan', 'Tonalá', 'Puerto Vallarta'],
  '16': ['Morelia', 'Uruapan', 'Zamora', 'Lázaro Cárdenas'],
  '17': ['Cuernavaca', 'Jiutepec', 'Cuautla'],
  '18': ['Tepic', 'Bahía de Banderas'],
  '19': ['Monterrey', 'Guadalupe', 'Apodaca', 'Santa Catarina'],
  '20': ['Oaxaca', 'Puerto Escondido', 'Huatulco'],
  '21': ['Puebla', 'Cholula', 'Tehuacán'],
  '22': ['Querétaro', 'San Juan del Río'],
  '23': ['Cancún', 'Playa del Carmen', 'Cozumel', 'Tulum'],
  '24': ['San Luis Potosí', 'Matehuala'],
  '25': ['Culiacán', 'Mazatlán', 'Los Mochis'],
  '26': ['Hermosillo', 'Ciudad Obregón', 'Navojoa'],
  '27': ['Villahermosa', 'Comalcalco'],
  '28': ['Ciudad Victoria', 'Tampico', 'Matamoros', 'Nuevo Laredo'],
  '29': ['Tlaxcala', 'Apizaco'],
  '30': ['Xalapa', 'Veracruz', 'Orizaba', 'Córdoba'],
  '31': ['Mérida', 'Cancún', 'Progreso'],
  '32': ['Zacatecas', 'Fresnillo', 'Jerez'],
};
